const animals = [
  {
    id: 0,
    image: [require("../../assets/images/animals/0_0.jpg")],
    shelter: "New Taipei City Zhonghe District Public Animal House",
    species: "dog",
    breed: "mixed",
    city: "New Taipei City",
    district: "Zhonghe District",
    place: " Zhonghe, New Taipei",
    gender: "female",
    tags: ["#Quiet", "#Medium Size"],
    age: "1~3 months",
  },
  {
    id: 1,
    image: [
      require("../../assets/images/animals/1_0.jpg"),
      require("../../assets/images/animals/1_1.jpg"),
      require("../../assets/images/animals/1_2.jpg"),
    ],
    shelter: "Taoyuan City Animal Protection Education Park",
    species: "dog",
    breed: "mixed",
    city: "Taoyuan City",
    district: "Xinwu District",
    place: "Xinwu, Taoyuan",
    gender: "male",
    tags: ["#Puppy"],
    age: "3~5 months",
  },
  {
    id: 2,
    image: [require("../../assets/images/animals/2_0.jpg")],
    shelter: "Miaoli County Government Environmental Protection Agency",
    species: "dog",
    breed: "mixed",
    city: "Miaoli County",
    district: "Tongluo Township",
    place: "Tongluo, Miaoli",
    gender: "female",
    tags: ["#Protective"],
    age: "3~5 months",
  },
  {
    id: 3,
    image: [require("../../assets/images/animals/3_0.jpg")],
    shelter: "Kaohsiung Animal Conservation Area",
    species: "dog",
    breed: "mixed",
    city: "Kaohsiung City ",
    district: "Gushan District",
    place: "Gushan, Kaohsiung",
    gender: "male",
    tags: ["#Play", "#Close to people"],
    age: "1~5 months",
  },
  {
    id: 4,
    image: [require("../../assets/images/animals/4_0.jpg")],
    shelter: "Hsinchu City Animal Protection Education Park",
    species: "dog",
    breed: "shiba",
    city: "Hsinchu City",
    district: "North District",
    place: "North, Hsinchu",
    gender: "female",
    tags: ["#Close to people"],
    age: "1~5 months",
  },
  {
    id: 5,
    image: [
      require("../../assets/images/animals/5_0.jpg"),
      require("../../assets/images/animals/5_1.jpg"),
      require("../../assets/images/animals/5_2.jpg"),
    ],
    shelter: "Tainan City Animal House Wanli Station",
    species: "dog",
    breed: "migru",
    city: "Tainan City",
    district: "South District",
    place: "South, Tainan",
    gender: "male",
    tags: ["#Play", "#Friendly"],
    age: "5~12 months",
  },
  {
    id: 6,
    image: [require("../../assets/images/animals/6_0.jpg")],
    shelter: "Kaohsiung Animal Conservation Area",
    species: "cat",
    breed: "kingira",
    city: "Kaohsiung City",
    district: "Gushan District",
    place: "Gushan, Kaohsiung",
    gender: "female",
    tags: ["#Not close to people"],
    age: "2~5 years",
  },
  {
    id: 7,
    image: [require("../../assets/images/animals/7_0.jpg")],
    shelter: "New Taipei City Banqiao District Public Animal House",
    species: "cat",
    breed: "mixed",
    city: "New Taipei City",
    district: "Benquai District",
    place: "Benquai, New Taipei",
    gender: "female",
    tags: ["#Introvert"],
    age: "2~5 years",
  },
  {
    id: 8,
    image: [require("../../assets/images/animals/8_0.jpg")],
    shelter: "Hsinchu City Animal Protection Education Park",
    species: "cat",
    breed: "mixed",
    city: "Hsinchu City",
    district: "North District",
    place: "North, Hsinchu",
    gender: "male",
    tags: ["#Cute", "#Play"],
    age: "5~ years",
  },
  {
    id: 9,
    image: [require("../../assets/images/animals/9_0.jpg")],
    shelter: "Taichung City Animal House Nantun Park",
    species: "cat",
    breed: "mixed",
    city: "Taichung City",
    district: "Nantun District",
    place: "Nantun, Taichung",
    gender: "female",
    tags: ["#Quiet"],
    age: "3~5 months",
  },
  {
    id: 10,
    image: [require("../../assets/images/animals/10_0.jpg")],
    shelter: "Kinmen County Animal shelter",
    species: "cat",
    breed: "mixed",
    city: "Kinmen County",
    district: "Jinhu Township",
    place: "Jinhu, Kinmen",
    gender: "female",
    tags: ["#Introvert"],
    age: "2~ yrs",
  },
];

export default animals;
