const animals = [
  {
    id: 0,
    image: [require("../../assets/images/animals/0_0.jpg")],
    shelter: "New Taipei City Zhonghe District Public Animal House",
    animal: "dog",
    breed: "mixed",
    city: "New Taipei City",
    gender: "f",
    tags: "#Quiet,Medium Size",
  },
  {
    id: 1,
    image: [
      require("../../assets/images/animals/1_0.jpg"),
      require("../../assets/images/animals/1_1.jpg"),
      require("../../assets/images/animals/1_2.jpg"),
    ],
    shelter: "Taoyuan City Animal Protection Education Park",
    animal: "dog",
    breed: "mixed",
    city: "Taoyuan City",
    gender: "m",
    tags: "#Puppy",
  },
  {
    id: 2,
    image: [require("../../assets/images/animals/2_0.jpg")],
    shelter: "Miaoli County Ecological Conservation Education Center",
    animal: "dog",
    breed: "mixed",
    city: "Miaoli County",
    gender: "f",
    tags: "#Protective",
  },
  {
    id: 3,
    image: [require("../../assets/images/animals/3_0.jpg")],
    shelter: "Kaohsiung City Shoushan Animal Protection Education Park",
    animal: "dog",
    breed: "mixed",
    city: "Kaohsiung City ",
    gender: "m",
    tags: "#Play, Close to people",
  },
  {
    id: 4,
    image: [require("../../assets/images/animals/4_0.jpg")],
    shelter: "Hsinchu City Animal Protection Education Park",
    animal: "dog",
    breed: "shiba",
    city: "Hsinchu City ",
    gender: "f",
    tags: "#Close to people",
  },
  {
    id: 5,
    image: [
      require("../../assets/images/animals/5_0.jpg"),
      require("../../assets/images/animals/5_1.jpg"),
      require("../../assets/images/animals/5_2.jpg"),
    ],
    shelter: "Tainan City Animal House Wanli Station",
    animal: "dog",
    breed: "migru",
    city: "Tainan City ",
    gender: "m",
    tags: "#Play, Friendly",
  },
  {
    id: 6,
    image: [require("../../assets/images/animals/6_0.jpg")],
    shelter: "Kaohsiung City Shoushan Animal Protection Education Park",
    animal: "cat",
    breed: "kingira",
    city: "Kaohsiung City ",
    gender: "f",
    tags: "",
  },
  {
    id: 7,
    image: [require("../../assets/images/animals/7_0.jpg")],
    shelter: "New Taipei City Banqiao District Public Animal House",
    animal: "cat",
    breed: "mixed",
    city: "New Taipei City",
    gender: "f",
    tags: "#Introvert",
  },
  {
    id: 8,
    image: [require("../../assets/images/animals/8_0.jpg")],
    shelter: "Hsinchu City Animal Protection Education Park",
    animal: "cat",
    breed: "mixed",
    city: "Hsinchu City ",
    gender: "m",
    tags: "#Cute, Play",
  },
  {
    id: 9,
    image: [require("../../assets/images/animals/9_0.jpg")],
    shelter: "Taichung City Animal House Nantun Park",
    animal: "cat",
    breed: "mixed",
    city: "Taichung City ",
    gender: "f",
    tags: "#Quiet",
  },
  {
    id: 10,
    image: [require("../../assets/images/animals/10_0.jpg")],
    shelter: "Kinmen County Animal shelter",
    animal: "cat",
    breed: "mixed",
    city: "Kinmen County ",
    gender: "f",
    tags: "#Introvert",
  },
];

export default animals;
