const favoritelist = [
  {
    id: 0,
    image: require("../../assets/images/animals/0_0.jpg"),
    shelter: "New Taipei City Zhonghe District Public Animal House",
    animal: "dog",
    breed: "mixed",
    city: "New Taipei City",
    district: "Zhonghe District",
    gender: "female",
    tags: ["#Quiet", "#Medium Size"],
  },
  {
    id: 5,
    image: require("../../assets/images/animals/5_1.jpg"),
    shelter: "Tainan City Animal House Wanli Station",
    animal: "dog",
    breed: "migru",
    city: "Tainan City",
    district: "South District",
    gender: "male",
    tags: ["#Play", "#Friendly"],
  },
  {
    id: 6,
    image: require("../../assets/images/animals/6_0.jpg"),
    shelter: "Kaohsiung Animal Conservation Area",
    animal: "cat",
    breed: "kingira",
    city: "Kaohsiung City",
    district: "Gushan District",
    gender: "female",
    tags: [],
  },
  {
    id: 3,
    image: require("../../assets/images/animals/3_0.jpg"),
    shelter: "Kaohsiung Animal Conservation Area",
    animal: "dog",
    breed: "mixed",
    city: "Kaohsiung City ",
    district: "Gushan District",
    gender: "male",
    tags: ["#Play", "#Close to people"],
  },
  {
    id: 4,
    image: require("../../assets/images/animals/4_0.jpg"),
    shelter: "Hsinchu City Animal Protection Education Park",
    animal: "dog",
    breed: "shiba",
    city: "Hsinchu City",
    district: "North District",
    gender: "female",
    tags: ["#Close to people"],
  },
];

export default favoritelist;
